Vagrant.configure("2") do |config|
  config.vm.define "web1" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "web2" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.network "private_network", ip: "192.168.56.11"
  end
end
